@TaskProcessor_HostAddress = http://localhost:5011
@TaskId = 8ba5e07b-9a89-47b0-b3f0-a65c33bbe0ec

# Should return 400 Bad Request
GET {{TaskProcessor_HostAddress}}/task
Accept: application/json

###

# Creates a new task
POST {{TaskProcessor_HostAddress}}/task
Accept: application/json

###

# Should return created task
GET {{TaskProcessor_HostAddress}}/task/{{TaskId}}
Accept: application/json

###
