@TaskProcessor_HostAddress = http://localhost:5011
@TaskId = 54616af0-cac6-4d1d-9ab7-5e26dac620a9

# Should return 400 Bad Request
GET {{TaskProcessor_HostAddress}}/task
Accept: application/json

###

# Creates a new task
POST {{TaskProcessor_HostAddress}}/task
Accept: application/json

###

# Returns status of task
GET {{TaskProcessor_HostAddress}}/task/{{TaskId}}
Accept: application/json

###
