#@TaskProcessor_HostAddress = http://localhost:5011
@TaskProcessor_HostAddress = http://127.0.0.1:8080
@TaskId = 0bcc8ed3-9830-46f3-9518-d1f811421447

# Should return 400 Bad Request
GET {{TaskProcessor_HostAddress}}/task
Accept: application/json

###

# Creates a new task
POST {{TaskProcessor_HostAddress}}/task
Accept: application/json

###

# Returns status of task
GET {{TaskProcessor_HostAddress}}/task/{{TaskId}}
Accept: application/json

###
